### ISSUE TITLE
Cannot compile on Slackware 13.1; complains of 'partial' ImageMagick

### ISSUE THREAD

**Issue by bf4** [gemhome/rmagick#12]
<a href="https://github.com/anoother"><img src="https://avatars.githubusercontent.com/u/205690?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [anoother](https://github.com/anoother)**
_Tuesday Jan 04, 2011 at 10:40 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/21_

----

Neither the gem, nor tarballs of 2.13.1 or 2.13.0 will compile:

 	 $ ruby setup.rb
	  ---> lib
	  ---> lib/rvg
	  <--- lib/rvg
	  <--- lib
	  ---> ext
	  ---> ext/RMagick
	  /usr/bin/ruby /home/ahmad/setup/software/ebookproduction/rmagick/	RMagick-2.13.1/ext/RMagick/extconf.rb
	  checking for Ruby version >= 1.8.5... *** /home/ahmad/setup/software/ebookproduction/rmagick/RMagick-2.13.1/ext/RMagick/extconf.rb failed ***
	  Could not create Makefile due to some reason, probably lack of necessary libraries and/or headers.  Check the mkmf.log file for more details.  You may need configuration options.
  
	  Provided configuration options:
		  --with-opt-dir
		  --without-opt-dir
		  --with-opt-include
		  --without-opt-include=${opt-dir}/include
		  --with-opt-lib
		  --without-opt-lib=${opt-dir}/lib
		  --with-make-prog
		  --without-make-prog
		  --srcdir=/home/ahmad/setup/software/ebookproduction/rmagick/RMagick-2.13.1/ext/RMagick
		  --curdir
		  --ruby=/usr/bin/ruby
	  /usr/lib/ruby/1.9.1/mkmf.rb:242:in `initialize': Permission denied - mkmf.log (Errno::EACCES)
		  from /usr/lib/ruby/1.9.1/mkmf.rb:242:in `open'
		  from /usr/lib/ruby/1.9.1/mkmf.rb:242:in `log_open'
		  from /usr/lib/ruby/1.9.1/mkmf.rb:247:in `open'
		  from /usr/lib/ruby/1.9.1/mkmf.rb:272:in `postpone'
		  from /usr/lib/ruby/1.9.1/mkmf.rb:669:in `checking_for'
		  from /home/ahmad/setup/software/ebookproduction/rmagick/RMagick-2.13.1/ext/RMagick/extconf.rb:114:in `<main>'
	  setup.rb:655:in `command': system("/usr/bin/ruby" "/home/ahmad/setup/software/ebookproduction/rmagick/RMagick-2.13.1/ext/RMagick/extconf.rb") failed (RuntimeError)
		  from setup.rb:660:in `ruby'
		  from setup.rb:1238:in `extconf'
		  from setup.rb:1230:in `config_dir_ext'
		  from setup.rb:1532:in `block in traverse'
		  from setup.rb:1549:in `dive_into'
		  from setup.rb:1530:in `traverse'
		  from setup.rb:1534:in `block (2 levels) in traverse'
		  from setup.rb:1533:in `each'
		  from setup.rb:1533:in `block in traverse'
		  from setup.rb:1549:in `dive_into'
		  from setup.rb:1530:in `traverse'
		  from setup.rb:1524:in `block in exec_task_traverse'
		  from setup.rb:1519:in `each'
		  from setup.rb:1519:in `exec_task_traverse'
		  from setup.rb:1223:in `exec_config'
		  from setup.rb:991:in `exec_config'
		  from setup.rb:812:in `invoke'
		  from setup.rb:772:in `invoke'
		  from setup.rb:1578:in `<main>'

Slackware 13.1 uses Ruby 1.9.1 and ImageMagick 6.5.9

Please help!

**Comment by vassilevsky** [comment]
I tested on this Vagrant box:

https://atlas.hashicorp.com/talosthoren/boxes/slackware-multilib

It contains Slackware 14.1

```
vagrant@slackware-multilib:~$ cat /etc/slackware-version
Slackware 14.1
```

Looks like they upgraded Ruby:

```
vagrant@slackware-multilib:~$ ruby -v
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
```

And RMagick installs fine on it:

```
vagrant@slackware-multilib:~$ sudo gem install rmagick
Fetching: rmagick-2.13.4.gem (100%)
Building native extensions.  This could take a while...
Please report any bugs. See https://github.com/gemhome/rmagick/compare/RMagick_2-13-2...master and https://github.com/rmagick/rmagick/issues/18
Successfully installed rmagick-2.13.4
1 gem installed
Installing ri documentation for rmagick-2.13.4...
Installing RDoc documentation for rmagick-2.13.4...
```

So the problem must be in Slackware 13 only.

Unfortunately, Atlas has no Slackware 13, because the image above is the only one there and http://www.vagrantbox.es has only one link — Slackware 13.37 which returns 404.

There is no Slackware template in Veewee:
https://github.com/jedi4ever/veewee/search?utf8=✓&q=slackware

I downloaded and ran the official `slackware64-13.1-install-dvd.iso` in a VirtualBox VM. It boots to root console and offers me to partition the drive and install the system. I'm not sure that I want to do that.

Slackware seems to be a regular Linux distribution though. The issue shouldn't be particular to Slackware.

I see the only problem in the provided log: insufficient permissions. I would recommend @anoother to use an RVM gemset for the project he is trying to set up:

https://rvm.io/gemsets/creating
