### ISSUE TITLE
JRuby RMagic undefined_symbol: rb_framce_last_func

### ISSUE THREAD

**Issue by bf4** [gemhome/rmagick#33]
<a href="https://github.com/daveed"><img src="https://avatars.githubusercontent.com/u/94511?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [daveed](https://github.com/daveed)**
_Thursday Apr 12, 2012 at 01:29 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/52_

----

I have an issue using the gem axlsx with JRuby. It seems to be an install problem.
Please have a look at https://github.com/randym/axlsx/issues/78 for my system details and error logs.

**Comment by vassilevsky** [comment]
OP's problem was solved in **axlsx** by not using RMagick :)

Looks like the problem was using JRuby.
RMagick uses `rb_frame_last_func` in its C extension.

MRI has this function:
https://github.com/ruby/ruby/search?utf8=✓&q=rb_frame_last_func

JRuby doesn't have it:
https://github.com/jruby/jruby/search?utf8=✓&q=rb_frame_last_func

We don't test on JRuby.
