### ISSUE TITLE
Adopt a code style guide

### ISSUE THREAD

**Issue by bf4** [gemhome/rmagick#58]
<a href="https://github.com/linduxed"><img src="https://avatars.githubusercontent.com/u/222098?" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [linduxed](https://github.com/linduxed)**
_Saturday Nov 02, 2013 at 15:11 GMT_
_Originally opened as https://github.com/rmagick/rmagick/issues/93_

----

Since I've started to look at some of the PRs here (along with the actual code) it would be nice to have an officially adopted style guide.

This would allow someone reviewing the code to point to specific issues in the code and reference the guide as a set of rules for what can and can't go into the code base.

I'm proposing the use of [thoughtbot's "guides" repository](https://github.com/thoughtbot/guides) as a start, since it's of high quality and constantly refined.

**Comment by linduxed** [comment]
Considering Hound was recently (at least so it seems) turned on for this project, I'm thinking it is even more relevant to settle for some style guide and add a `.hound.yml` that reflects this.

Currently we've got a `.rubocop.yml` that was auto-generated with `rubocop --auto-gen-config`, which isn't exactly the best thing to do considering there's a strong possibility there was **no** explicit style that was followed in the old code.

**Comment by mockdeep** [comment]
The existing `.rubocop.yml` file has all of the rules disabled for the moment. The idea was that they could be discussed individually as they are enabled.

**Comment by vassilevsky** [comment]
Yes, I enabled Hound because why not :)

I had no idea Thoughbot prefers double quotes everywhere. I have now committed the `.hound.yml` file that points to `.rubocop.yml`.

I recently deleted a lot of rules from `.rubocop.yml` and ran `rubocop -a` after each deletion, and committed the changes. So, Ruby code in this repo isn't as bad as it was already :) I did not make controversial changes, just the most obvious ones.

I think that we need to continue deleting stuff from `.rubocop.yml`. Also, watch out for Hound comments that are wrong and fix something in the config so that they disappear or no longer added.

**Comment by mockdeep** [comment]
Yeah, I was going to try to get the test coverage up before jumping into rubocop completely, but most of it should be harmless. First thing is converting over to RSpec... not enough time...

**Comment by bf4** [comment]
Sounds good.  If you want to introduce rspec just have it run with
testunit, and occasionally move specs over :)

**Comment by mockdeep** [comment]
Yep, that's the plan.

**Comment by vassilevsky** [comment]
`.rubocop.yml` is in place.
Hound is checking PRs, using it.

I think this is no longer an issue.
